# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------

project = 'GIS for Land Administration'
copyright = '2020, Andre da Silva Mano'
author = 'Andre da Silva Mano'
release = '1'

# -- General configuration ---------------------------------------------------

import os
import sys
import sphinx_rtd_theme
#sphinx_outputdir = "_build/html"
sys.path.append(os.path.abspath("./_ext"))
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ['sphinx_rtd_theme']

# Name of the master document.
master_doc = 'index'

# Add any paths that contain templates here, relative to this directory.
#templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = '[en]'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['_static/assets/data-links-gis.rst', '_assets/ltb-links-gis.rst' ]

#in readthedocs.org there occurs "contents.rst not found" error. The master document has to be specified to avoid that error

#this is to allow figure numbering and referencing
numfig = True

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = "sphinx_rtd_theme"


###########################################################
# Target link-files
link_file = ['_static/assets/ltb-links-gis.rst', '_static/assets/data-links-gis.rst']

# Allows storing external links in separated rst
rst_epilog=""

# Read links in the from the target files
for file in link_file:
    with open(file) as f:
        rst_epilog += f.read()

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

# Configure paper size, font size, preamble options, etc.
latex_elements = {
    'figure_align': 'H',
    'preamble': '''
        \\usepackage{float}
        ''',
}


